[phases.setup]
nixPkgs = ["...", "php83", "php83Packages.composer", "nodejs"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build"
]

[start]
cmd = "bash start.sh"
